In [ ]:
#LECTURE 1

In [1]:
#pytorch pre-installed on colab
import torch

In [11]:
#A tensor is a number, vector, matrix, or any n-dimensional array. Let's create a tensor with a single number.

# Number
t1 = torch.tensor(4.)#4. short for 4.0
print(t1)
print(t1.dtype)

# Vector
t2 = torch.tensor([1., 2, 3, 4])
print(t2)

# Matrix
t3 = torch.tensor([[5., 6], 
                   [7, 8], 
                   [9, 10]])
print(t3)

# 3-dimensional array
t4 = torch.tensor([
    [[11, 12, 13], 
     [13, 14, 15]], 
    [[15, 16, 17], 
     [17, 18, 19.]]])
print(t4)

print("")
print(t1)
print(t1.shape)

print("")
print(t2)
print(t2.shape)

print("")
print(t3)
print(t3.shape)

print("")
print(t4)
print(t4.shape)

tensor(4.)
torch.float32
tensor([1., 2., 3., 4.])
tensor([[ 5.,  6.],
        [ 7.,  8.],
        [ 9., 10.]])
tensor([[[11., 12., 13.],
         [13., 14., 15.]],

        [[15., 16., 17.],
         [17., 18., 19.]]])

tensor(4.)
torch.Size([])

tensor([1., 2., 3., 4.])
torch.Size([4])

tensor([[ 5.,  6.],
        [ 7.,  8.],
        [ 9., 10.]])
torch.Size([3, 2])

tensor([[[11., 12., 13.],
         [13., 14., 15.]],

        [[15., 16., 17.],
         [17., 18., 19.]]])
torch.Size([2, 2, 3])


In [5]:
#not possible to create tensors with an improper shape.
# Matrix
t5 = torch.tensor([[5., 6, 11], 
                   [7, 8], 
                   [9, 10]])
t5

ValueError: ignored

In [13]:
#Operations and Gradients

# Create tensors.
x = torch.tensor(3.)
# we can automatically compute the derivative of y w.r.t. the tensors that have requires_grad set to True i.e. w and b. 
w = torch.tensor(4., requires_grad=True)
b = torch.tensor(5., requires_grad=True)
print(x,w,b)

# Arithmetic operations
#3*4+5
y = w * x + b
print(y)

# Compute derivatives on wx+b
y.backward()

# Display gradients
print('dy/dx:', x.grad)#No requires_grad
print('dy/dw:', w.grad)#d(3w+5)/dw
print('dy/db:', b.grad)#d(3*4+b)/db

tensor(3.) tensor(4., requires_grad=True) tensor(5., requires_grad=True)
tensor(17., grad_fn=<AddBackward0>)
dy/dx: None
dy/dw: tensor(3.)
dy/db: tensor(1.)


In [12]:
#Tesnor functions

# Create a tensor with a fixed value for every element
t6 = torch.full((3, 2), 42)
print(t6)

# Concatenate two tensors with compatible shapes
t7 = torch.cat((t3, t6))
print(t7)

# Compute the sin of each element
t8 = torch.sin(t7)
print(t8)

# Change the shape of a tensor
t9 = t8.reshape(3, 2, 2)
print(t9)

tensor([[42, 42],
        [42, 42],
        [42, 42]])
tensor([[ 5.,  6.],
        [ 7.,  8.],
        [ 9., 10.],
        [42., 42.],
        [42., 42.],
        [42., 42.]])
tensor([[-0.9589, -0.2794],
        [ 0.6570,  0.9894],
        [ 0.4121, -0.5440],
        [-0.9165, -0.9165],
        [-0.9165, -0.9165],
        [-0.9165, -0.9165]])
tensor([[[-0.9589, -0.2794],
         [ 0.6570,  0.9894]],

        [[ 0.4121, -0.5440],
         [-0.9165, -0.9165]],

        [[-0.9165, -0.9165],
         [-0.9165, -0.9165]]])


In [ ]:
#Numpy is a popular open-source library used for mathematical and scientific computing in Python. 
#It enables efficient operations on large multi-dimensional arrays and has a vast ecosystem of supporting libraries, including:
#Pandas for file I/O and data analysis
#Matplotlib for plotting and visualization
#OpenCV for image and video processing
#PyTorch interoperates well with Numpy to leverage its existing ecosystem of tools and libraries.

In [ ]:
#Create Array
import numpy as np

x = np.array([[1, 2], [3, 4.]])
print(x)

# Convert the numpy array to a torch tensor.
y = torch.from_numpy(x)
print(y)

#Verify if have similar datatype
print(x.dtype, y.dtype)

# Convert a torch tensor to a numpy array
z = y.numpy()
print(z)

#Why Pytorch
#Autograd: The ability to automatically compute gradients for tensor operations is essential for training deep learning models.
#GPU Support